### ISSUE TITLE
How to deal with the old minimumClusterSize option?

### ISSUE THREAD

**Issue by thexs-dev** [googlemaps/js-markerclusterer#111]
In the previous `js-markerclustererplus` there is an option `minimumClusterSize` that sets
> The minimum number of markers needed in a cluster before the markers are hidden and a cluster marker appears.
https://googlemaps.github.io/js-markerclustererplus/interfaces/MarkerClustererOptions.html#minimumClusterSize

How to set that `minimumClusterSize` option in this new library?

**Comment by jpoehnelt** [comment]
You can pass options to the https://www.npmjs.com/package/supercluster algorithm

```js

import {MarkerClusterer, SuperClusterAlgorithm} from '@googlemaps/markerclusterer';

new MarkerClusterer({
  algorithm: new SuperClusterAlgorithm({minPoints: 1234}),
})
```

**Comment by maximstrukov** [comment]
> You can pass options to the https://www.npmjs.com/package/supercluster algorithm
> 
> ```js
> import {MarkerClusterer, SuperClusterAlgorithm} from '@googlemaps/markerclusterer';
> 
> new MarkerClusterer({
>   algorithm: new SuperClusterAlgorithm({minPoints: 1234}),
> })
> ```

Hi @jpoehnelt , I'm trying to follow that approach to be able to use the **minPoints** parameter, but I fail to import the **SuperClusterAlgorithm**.
Right now I just have this script added on me page:
`<script src="https://unpkg.com/@googlemaps/markerclusterer/dist/index.min.js"></script>`
and I can't use `algorithm: new SuperClusterAlgorithm({minPoints: 1234}),` as it says **SuperClusterAlgorithm** is not defined.

If I try exactly the same you mentioned above:
`import {MarkerClusterer, SuperClusterAlgorithm} from '@googlemaps/markerclusterer';`
then my webpack can't compile that saying that "@googlemaps/markerclusterer" can not be found.

My entire script that is using the markerclusterer is like that:

```
    const renderer = {
        render: function ({ markers, count, position }) {
            const clusterMarker = new google.maps.Marker({
               // ..... specifying the properties like label, position, title, icon........
            });
            return clusterMarker;
        }
    };

    // Add a marker clusterer to manage the markers.
    // See: https://googlemaps.github.io/js-markerclusterer/
    landingMarkerCluster = new markerClusterer.MarkerClusterer({
        map: mapPins,
        markers: landingMarkers,
        renderer: renderer,
        onClusterClick: function onClusterClick(event, cluster, map) {
           // .............
        }
    });
```

Could you advise how to resolve it? Thank you!
