### ISSUE TITLE
Fractional Zoom and SuperCluster

### ISSUE THREAD

**Issue by zjr8** [googlemaps/js-markerclusterer#112]
Hi Team,

Thanks for open sourcing / making your project public. 

Not sure if this is a bug or if I am just having a Sunday Funday. 

There appears to be an issue with the default cluster algorithm when applied to a map that is vector  based instead of raster based when updating clusters on click. 

I am not 100% sure if I am debugging the issue correctly but it appears to be caused by/when zoom is not an integer value when tilted etc. Overriding the SuperClusterAlgorithm cluster function to round map.getZoom() to an integer seems to solve the issue more or less but not sure of any other issues it may cause or if it would be better to open an issue with the Super Cluster library team as the error seems to occur  in the getClusters function on const tree = this.trees[this._limitZoom(zoom)] line.

**Comment by jpoehnelt** [comment]
Yeah, fractional zoom is probably an issue since SuperCluster is going to require discrete dimensions for its kd tree.

**Comment by jpoehnelt** [comment]
Thanks for reporting. Will be published in the next release shortly!
