### ISSUE TITLE
Library not working with Angular Google Maps component

### ISSUE THREAD

**Issue by Marcinowy** [googlemaps/js-markerclusterer#130]
Hey,
I came here because of some bugs in old js-markerclustererplus library ([this issue](https://github.com/googlemaps/js-markerclustererplus/issues/300)). However, when I tried to use this lib with Angular Google Maps component, it's throwing errors. I tried to "build a bridge" in ugly way to make the new lib working, but with no effects. This is my tries:
`window.MarkerClusterer = window.markerClusterer.MarkerClusterer;
window.MarkerClusterer.prototype.repaint = window.MarkerClusterer.prototype.render;`
I know the chances to update Google Maps component are very low, so I'm asking you to adapt old methods.

Thanks a lot!

**Comment by jpoehnelt** [comment]
The interface is not directly compatible. You will likely need to fork agm.

**Comment by jpoehnelt** [comment]
Forking shouldn't be much of an issue since agm is not maintained.

**Comment by jpoehnelt** [comment]
Assuming this is AGM and not https://www.npmjs.com/package/@angular/google-maps. If it is the latter, support should be added there.
