### ISSUE TITLE
Custom Icon for MarkerCluster

### ISSUE THREAD

**Issue by KAPILBADWAL** [googlemaps/js-markerclusterer#141]
I gave been trying to add custom icons for Marker Clusters and am not able to find the feature.

The official documentation mentions the below (https://developers.google.com/maps/documentation/javascript/marker-clustering#npm_1)
Customize the cluster icon through the renderer interface.
But the option is not visible in the API.
Any help is much appreciated.

**Comment by jpoehnelt** [comment]
The reference docs:

https://googlemaps.github.io/js-markerclusterer/interfaces/Renderer.html
https://googlemaps.github.io/js-markerclusterer/classes/MarkerClusterer.html

Examples: 

https://googlemaps.github.io/js-markerclusterer/public/renderers/
