### ISSUE TITLE
Possible to create a StackBlitz/Plunker example?

### ISSUE THREAD

**Issue by VashJuan** [googlemaps/js-markerclusterer#155]
Thanks for stopping by to let us know something could be better!

 **Is your feature request related to a problem? Please describe.**
I'm not sure how to "approach" (i.e., build and run) the examples in your examples directory. I'm sure its trivial, but where do I get started?!

For instance your ReadMe has:
sample.component.ts as:
```
import { MarkerClusterer } from "@googlemaps/markerclusterer";

// use default algorithm and renderer
const markerCluster = new MarkerClusterer({ map, markers });
```
Obviously there is a lot more to producing a simple map than this...

 **Describe the solution you'd like**
It would be nice to have a StackBlitz (or other easy isolated dev environment, like Plunker or CodePen) examples to ensure I'm setting up my environment correctly, have the right versions of related packages, and haven't made any typos... 

 **Describe alternatives you've considered**
I'm just browsing for full code examples to insert into my project as a starting point...

 **Additional context**

**Comment by VashJuan** [comment]
At least add a link to this:
https://developers.google.com/maps/documentation/javascript/marker-clustering
which provides much more detail!

**Comment by VashJuan** [comment]
Oh, here is a sample to refer to...
https://stackblitz.com/github/googlemaps/js-samples/tree/sample-marker-clustering

**Comment by jpoehnelt** [comment]
https://developers.google.com/maps/documentation/javascript/marker-clustering#try-sample should have different playgrounds to test out this library.

![Screen Shot 2022-02-22 at 9 21 24 AM](https://user-images.githubusercontent.com/3392975/155174246-f0f41523-1a92-44e0-8bcf-7b2da62f23b5.png)

**Comment by bitbytebit1** [comment]
Stackblitz is failing with the error 
`Google Maps JavaScript API error: RefererNotAllowedMapError
https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error
Your site URL to be authorized: https://zzmirxyza--github--3000.local-corp.webcontainer.io/`
