### ISSUE TITLE
Another clusterer option based on data points instead of map markers ...

### ISSUE THREAD

**Issue by bdcoder2** [googlemaps/js-markerclusterer#158]
Just another option for those looking to manage a large number of data points with Google maps:

[https://github.com/bdcoder2/grid_clusterer](https://github.com/bdcoder2/grid_clusterer)

If interested, I would be more than happy to send you the source code (Typescript) for inclusion as an option for Google maps.

**Comment by jpoehnelt** [comment]
Thanks for sharing.
