### ISSUE TITLE
Methods for customizing a click on a cluster

### ISSUE THREAD

**Issue by Annetastar** [googlemaps/js-markerclusterer#191]
Hello. Thanks for the awesome library!
Tell me how to make a smooth zoom when clicking on a cluster?
Can't understand from the documentation. 

Thank you!

![Снимок экрана 2022-01-19 в 16 27 23](https://user-images.githubusercontent.com/50481390/150151045-272f4e47-20d2-438d-b23b-df4464735486.png)

**Comment by jpoehnelt** [comment]
What do you mean by "smooth zoom"?

**Comment by Annetastar** [comment]
> What do you mean by "smooth zoom"?

In general, how can you customize a click on a cluster? For example, zoom slowly to the markers in the cluster or fast, or adjust the zoom scale?

**Comment by karlxavier** [comment]
hi! is there any other way for this library to catch the `mouseover` event for each cluster?

**Comment by JorgeSivil** [comment]
I did something like this

```
const onClusterClick = (
                event: google.maps.MapMouseEvent,
                cluster: Cluster,
                map: google.maps.Map,
            ) => {
                const markers = cluster.markers;
                const bounds = new google.maps.LatLngBounds();
                if (markers) {
                    for (let i = 0; i < markers.length; i++) {
                        bounds.extend(
                            markers[i].position as google.maps.LatLng,
                        );
                    }
                    map.setCenter(cluster.position);
                    const boundsZoomLevel = getBoundsZoomLevel(
                        bounds,
                        map.getDiv().getBoundingClientRect(),
                    );
                    const initialZoom = map.getZoom() || 9;
                    for (let i = initialZoom; i <= boundsZoomLevel; i = i + 2) {
                        setTimeout(
                            () => setZoom(map, i),
                            150 * (i - initialZoom),
                        );
                    }
                }
            };
 ```

Less than 150ms makes it not smooth.

https://stackoverflow.com/questions/6048975/google-maps-v3-how-to-calculate-the-zoom-level-for-a-given-bounds
