### ISSUE TITLE
library mutates its data (Markers)

### ISSUE THREAD

**Issue by maapteh** [googlemaps/js-markerclusterer#201]
Using the latest version of this library i noticed the library mutates the markers provided. Thats fine inside a React Class component, but when i want to have a Functional component i noticed i will endup with both markers being painted since the library will mutate the collection of markers.

Is it possible the library, when initiating a new Clusterer, will return its (mutated) markers? So i can update state?

**Comment by jpoehnelt** [comment]
The only mutation is adding and removing the markers from the map. This is required functionality for the library. This may happen on every pan of the map or change of zoom.

There should be no difference in functionality between a React class and a functional component. It is likely the case that a hook is required such as `useEffect` to provide the same pattern as the React class methods. I'm going to close for now, please feel free to reopen with a codesandbox or similar detailing any specific issue/feature with this library.

**Comment by maapteh** [comment]
If i set the markers as a state using useState then that collection will never be mutated, because you mutate them! That will lead in a cluster AND some markers :) Mutating data is fine (as in fine in case of not rendering markers its the only solution :)) as long as you return the mutated result so the component can also update its state!

I will see if i find time, i cant give my client code :( i hoped mutation argument would be enough :)

**Comment by jpoehnelt** [comment]
Would you want the cluster markers returned too? These are generated by the library.

React by default does not do a deep diff, the returned markers will always be an array with the same objects and length irregardless of whether setMap(null) or setMap(map) has been called. A high level overview of your component structure would be helpful to understand your use case.

**Comment by maapteh** [comment]
I will try to make a simple reproduction :) That indeed talks better

**Comment by jpoehnelt** [comment]
Please reopen if more information provided.
