### ISSUE TITLE
Documentation adjustment for the default algorithm of the MarkerClustererOptions

### ISSUE THREAD

**Issue by seb9465** [googlemaps/js-markerclusterer#23]
Hi,

Very simple thing : in the documentation for the [MarkerClustererOptions](https://googlemaps.github.io/js-markerclusterer/interfaces/MarkerClustererOptions.html), it says the default algorithm is GridAlgorithm but on [line 81 of the markerclusterer.ts file](https://github.com/googlemaps/js-markerclusterer/blob/b12c38d/src/markerclusterer.ts#L81), the SuperClusterAlgorithm is default. It took me some time to figure this out since my implementation wasn't working as expected.

Thanks !

**Comment by jpoehnelt** [comment]
Thanks for reporting. Sorry for the time lost!
