### ISSUE TITLE
getMarkers()?

### ISSUE THREAD

**Issue by morrow95** [googlemaps/js-markerclusterer#233]
Old version had a `getMarkers()` which would return marker information from the clicked on cluster.  Is there no such ability in this version?

In my case I had clusters which could never be zoomed in enough to separate them into markers.  For example, multiple people at the same lat/lng each with their own marker.  When the maxzoom was reached on click of the cluster I would show an info window popup that broke down the information of the different markers in that cluster.

**Comment by jpoehnelt** [comment]
The renderer provides the ability to customize cluster marker display and cluster onclick logic.

**Comment by morrow95** [comment]
What are the chances of throwing up a demo using the algorithm and render options so we can actually see some example code of these being used?
