### ISSUE TITLE
radius parameter in the SuperClusterAlgorithmOptions

### ISSUE THREAD

**Issue by seb9465** [googlemaps/js-markerclusterer#25]
Hi, me again !

Do you think it is possible to add a `radius` parameter in the Super Cluster Algorithm Options ? I saw it is fixed to 60 in the [supercluster.ts file on line 41](https://github.com/googlemaps/js-markerclusterer/blob/9411b35d8c470ea9a2df696a4f813aef8c6e12ec/src/algorithms/supercluster.ts#L41). If I could have set my own value, I would have go with that algorithm instead of the Grid Algorithm. With the grid one, I can set a grid size.

Thanks 🙂 !

**Comment by jpoehnelt** [comment]
That's a mistake. Fix incoming.
