### ISSUE TITLE
Prevent adding duplicate markers to a MarkerClusterer instance

### ISSUE THREAD

**Issue by seb9465** [googlemaps/js-markerclusterer#27]
I think it could be interesting to have a mechanism that detects duplicate markers when using the function `addMarker` of a _MarkerClusterer_ instance.

**Comment by jpoehnelt** [comment]
duplicate as in exact marker or one that shares same location? The first seems more reasonable to implement, the latter probably would be too opinionated.

**Comment by seb9465** [comment]
> duplicate as in exact marker or one that shares same location? The first seems more reasonable to implement, the latter probably would be too opinionated.

Sorry for the late response, but yes, "duplicate" as in the exact same marker. 

Thanks 🙂 !

**Comment by jpoehnelt** [comment]
Not a problem! Let me know if there is anything else that could be improved.
