### ISSUE TITLE
No implementation for maxZoom

### ISSUE THREAD

**Issue by VishnAndr** [googlemaps/js-markerclusterer#374]
Looks like the markerclusterer misses maxZoom option.
It is there in the comments. But no footprint in the code.
https://github.com/googlemaps/js-markerclusterer/blob/ba991e3e5654cea7bee8c828aaa5c30e2f308574/src/markerclusterer.ts#L74

**Comment by hknaksu** [comment]
This is how I have it working:
const algo = new  markerClusterer.SuperClusterAlgorithm({maxZoom: 12, minPoints: 10})
this.markerClusterer = new markerClusterer.MarkerClusterer({map: this.gMap, markers: [], algorithm: algo});
