### ISSUE TITLE
Add "Other Clustering Implementations" heading to the end of README.md ...

### ISSUE THREAD

**Issue by bdcoder2** [googlemaps/js-markerclusterer#376]
Just an idea - For completeness, add a new heading at the end of README.md to list other clustering implementations, for example:

### Other Clustering Implementations (not supported by Google)

- Grid Clusterer
   - Project: [https://github.com/bdcoder2/grid_clusterer](https://github.com/bdcoder2/grid_clusterer)
   - Demo: [https://bdcoder2.github.io/grid_clusterer/index.html](https://bdcoder2.github.io/grid_clusterer/index.html)
   
- Other Implementation
   - Project: [link]
   - Demo: [link]

**Comment by amuramoto** [comment]
Thanks for the suggestion! Unfortunately, we won't be able to do this. Since we aren't able to fully vet the other clustering implementations we can't safely point to them as alternative options.
