### ISSUE TITLE
Compare 2 types of markers with diferent icons or colors

### ISSUE THREAD

**Issue by rafwell** [googlemaps/js-markerclusterer#393]
Hi guys.

How can I compare 2 types of markers? Example, I have a lot of bananas's and watermelons's makers around the world. I wanna compare the bananas x watermelons, suposing the banana marker is yellow and watermelon is red, visually I can get it.

It's possible?

**Comment by amuramoto** [comment]
You should be able to call `getIcon()` on the `Marker` instance and compare the results.
