### ISSUE TITLE
New version has not yet been published on NPM

### ISSUE THREAD

**Issue by mihilt** [googlemaps/js-markerclusterer#398]
I checked it already solved the #232 issue and merged the new code, and that it released the package to this github repository with v2.0.9.

However, it seems that the version has not yet been updated in node package manager.

Even with a new installation of the package in the new project, the version of the package shown in the package.json file is still v2.0.8 and also on the npm site.

Check it please.

<kbd>![image](https://user-images.githubusercontent.com/50368758/179700615-28704cfa-87e8-440b-81c8-ae7ccbed6767.png)</kbd>

**Comment by amuramoto** [comment]
release 2.0.10

**Comment by mihilt** [comment]
Yup I also can notice it is released. But it happened only in this repository.

Please check url below and publish in node package manager.
https://www.npmjs.com/package/@googlemaps/markerclusterer
<kbd>![image](https://user-images.githubusercontent.com/50368758/182539674-6d5816b8-f5e0-45de-916b-352ebe46b2f5.png)</kbd>
