### ISSUE TITLE
New version still has not yet been published on NPM

### ISSUE THREAD

**Issue by BoyeTRev** [googlemaps/js-markerclusterer#408]
The latest version of the package v2.0.10 has not been published yet on npm, the latest published version is still on v2.0.8.

**Screenshot**

<img width="350" alt="Screen Shot 2022-08-03 at 11 08 07 AM" src="https://user-images.githubusercontent.com/31700848/182643224-bf565c6a-11a2-4dc1-a67c-d5e93b00f41a.png">

<img width="1367" alt="Screen Shot 2022-08-03 at 11 08 19 AM" src="https://user-images.githubusercontent.com/31700848/182643249-f80107eb-5ee9-4a35-81c5-09b9828845fb.png">

I see this issue was reported in #398 but it was closed, it hasn't been resolved yet.

Can we please publish the latest version to npm as it contains fixes for several bugs we are facing now

**Comment by amuramoto** [comment]
2.0.10 is now released
