### ISSUE TITLE
mouseover events for clusters

### ISSUE THREAD

**Issue by GeirFjaerli** [googlemaps/js-markerclusterer#426]
Hi. There does not seem to be a way to attach events other than click to clusters. What I want is to show an infobox or similar listing the places of the markers in the cluster the mouse is currently hovering. I do not want to hijack the click event, that should work as intended. Edit: But it would make sense if the user could see the contents of each cluster without having to click in and then zoom out of each of them. In my case there are quite a few clusters...

But as far as I can tell there is no support for mouseover events for clusters. Stackoverflow threads on the subject seems to be years old and outdated, and suggestions found there and elsewhere does not work for me. 

If there is a way, I'd be grateful to know, and if not, maybe this is a sensible addition to the library.

Geir :)

**Comment by GeirFjaerli** [comment]
Update: Then upon reading the docs I realised you can in fact replace the default renderer that creates the marker for the cluster. And so I was able to simply concatenate the marker labels into a string with line breaks and assign that as the marker title for the cluster. My problem solved. 

Not entirely sure how to proceed on GitHub, this is my first issue. But the enhancement is no longer needed...

Geir :)

**Comment by coderwyd** [comment]
> Hi. There does not seem to be a way to attach events other than click to clusters. What I want is to show an infobox or similar listing the places of the markers in the cluster the mouse is currently hovering. I do not want to hijack the click event, that should work as intended. Edit: But it would make sense if the user could see the contents of each cluster without having to click in and then zoom out of each of them. In my case there are quite a few clusters...
> 
> But as far as I can tell there is no support for mouseover events for clusters. Stackoverflow threads on the subject seems to be years old and outdated, and suggestions found there and elsewhere does not work for me.
> 
> If there is a way, I'd be grateful to know, and if not, maybe this is a sensible addition to the library.
> 
> Geir :)

I also encountered the same problem. Have you solved it now.

**Comment by GeirFjaerli** [comment]
> I also encountered the same problem. Have you solved it now.

Hi, that depends on the problem. I wrote in my previous reply I found a way to show the cluster marker title with the places it contains. If your issue is wanting mouseover or other events, then no, there is no way that I have found. 

But if it is the first then here is how:
When you create a new markerclusterer you can specify an object in your script file that replaces the standard renderer:

`myCluster = new markerClusterer.MarkerClusterer({ map: myMap, renderer: myCustomRenderer });`

Now Google has posted the code of the default renderer here: https://googlemaps.github.io/js-markerclusterer/classes/DefaultRenderer.html

Add your custom object (myCustomRenderer above) to your script, with a method with the same name and parameters as the default one:

```
const myCustomRenderer = {
   render(cluster, stats) { code here } 
}
```

The markers is an array in the first parameter: cluster.markers, so you can simply loop and concatenate them with line breaks into a variable, say named clusterTitle. Use backslash n for line breaks. You want the label property of the marker, so something like this:

```
let clusterTitle = '';
cluster.markers.forEach(el => (clusterTitle += `${el.label}\n`));
```

Then add the default code from the link above, with one addition. In the marker definition, add a title property set to clusterTitle:

```
const marker = new google.maps.Marker({
    position,
    title: clusterTitle,
    icon: ...
})
```

And then finally at the end of the render method you must return the marker:

`return marker;`

And that is it. You should now have an object like this:

```
const myCustomRenderer = {
   render(cluster, stats) { 
      let clusterTitle = '';
      cluster.markers.forEach(el => (clusterTitle += `${el.label}\n`));

      // Default code goes here, with added title property

      return marker;
   } 
}
```

Now whatever you put into clusterTitle will show as a popup title when you hower the cluster. Then of course you are free to alter or embellish the default code anyway you like, change the icons or whatever. I have instances where there may be a hundred markers in one cluster when you zoom out, so I have added a max to how many are added to the title.

Hope that helps!

Geir :)

**Comment by coderwyd** [comment]
> > I also encountered the same problem. Have you solved it now.我也遇到了同样的问题，你现在解决了吗。
> 
> Hi, that depends on the problem. I wrote in my previous reply I found a way to show the cluster marker title with the places it contains. If your issue is wanting mouseover or other events, then no, there is no way that I have found.
> 
> 嗨，那要看是什么问题了。我在之前的回复中写道，我找到了一种方法来显示集群标记标题及其包含的位置。如果你的问题是想要鼠标悬停或其他事件，那么不，没有办法，我已经找到。
> 
> But if it is the first then here is how: 但如果它是第一个，那么这里是如何: When you create a new markerclusterer you can specify an object in your script file that replaces the standard renderer: 当您创建一个新的 markercluster 时，您可以在脚本文件中指定一个替换标准呈现程序的对象:
> 
> `myCluster = new markerClusterer.MarkerClusterer({ map: myMap, renderer: myCustomRenderer });`
> 
> MyCluster = new markerCluster.MarkerClusterer ({ map: myMap，renderer: myCustomRenderer }) ;
> 
> Now Google has posted the code of the default renderer here: https://googlemaps.github.io/js-markerclusterer/classes/DefaultRenderer.html
> 
> 现在谷歌已经在这里发布了默认渲染器的代码: https://googlemaps.github.io/js-markerclusterer/classes/defaultrenderer.html
> 
> Add your custom object (myCustomRenderer above) to your script, with a method with the same name and parameters as the default one:
> 
> 将您的自定义对象(上面的 myCustomRenderer)添加到脚本中，使用与默认方法具有相同名称和参数的方法:
> 
> ```
> const myCustomRenderer = {
>    render(cluster, stats) { code here } 
> }
> ```
> 
> The markers is an array in the first parameter: cluster.markers, so you can simply loop and concatenate them with line breaks into a variable, say named clusterTitle. Use backslash n for line breaks. You want the label property of the marker, so something like this:
> 
> 标记是第一个参数: Cluster.marks 中的一个数组，因此您可以简单地循环它们，并用换行符将它们连接到一个变量中，比如名为 ClusterTitle 的变量。使用反斜杠 n 表示换行符。您需要标记的 label 属性，如下所示:
> 
> ```
> let clusterTitle = '';
> cluster.markers.forEach(el => (clusterTitle += `${el.label}\n`));
> ```
> 
> Then add the default code from the link above, with one addition. In the marker definition, add a title property set to clusterTitle. Edit: You must also get the position out of the cluster parameter:
> 
> 然后从上面的链接中添加默认代码，添加一个。在标记定义中，将 title 属性集添加到 ClusterTitle。编辑: 您还必须得到集群参数的位置:
> 
> ```
> const position = cluster.position;
> const marker = new google.maps.Marker({
>     position,
>     title: clusterTitle,
>     icon: ...
> })
> ```
> 
> And then finally at the end of the render method you must return the marker:
> 
> 最后，渲染方法的结尾必须返回标记:
> 
> `return marker;`
> 
> And that is it. You should now have an object like this:
> 
> 就是这样，你现在应该有一个这样的物体:
> 
> ```
> const myCustomRenderer = {
>    render(cluster, stats) { 
>       let clusterTitle = '';
>       cluster.markers.forEach(el => (clusterTitle += `${el.label}\n`));
> 
>       // Default code goes here, with added title property
> 
>       return marker;
>    } 
> }
> ```
> 
> Now whatever you put into clusterTitle will show as a popup title when you hower the cluster. Then of course you are free to alter or embellish the default code anyway you like, change the icons or whatever. I have instances where there may be a hundred markers in one cluster when you zoom out, so I have added a max to how many are added to the title. Edit: You will find the number of markers in cluster.count.
> 
> 现在，当您对集群进行降温操作时，您放入 ClusterTitle 的任何内容都会显示为一个弹出式标题。然后，当然你可以自由地改变或修饰默认代码，无论你喜欢什么，改变图标或任何东西。我有一些实例，当你缩小时，一个集群中可能有一百个标记，所以我在标题中添加了一个最大值。编辑: 您将找到 Cluster.count 中的标记数。
> 
> Hope that helps! 希望能帮上忙
> 
> Geir :) 盖尔:)

I solved my problem by adding a custom renderer and adding a mouseover listener to Marker to control the InfoWindow display.
```
const myCustomRenderer = {
  render: () => {
    const marker = new google.maps.Marker(...)
    marker.addListener('mouseover', () => {
      infoWindow.open(...)
    })
    marker.addListener('mouseout', () => {
      infoWindow.close()
    })
    return marker
  },
}
```

Thanks for the example, it's great!

**Comment by GeirFjaerli** [comment]
You're welcome. And I see that you add a listener in the custom renderer. I never thought of that, so thanks to you too. (My original idea was a info window too, but I skipped that when I realised the title attribute would solve my problem.) Now I know that it can be done, should I ever need it! :)

Geir :)

BTW: You may want to edit your reply and delete the quote. (Unless the translation is for the benefit of someone else.) No need to post the same contents twice...

**Comment by amuramoto** [comment]
Thanks @GeirFjaerli and @coderwyd for providing your solutions! =)
