### ISSUE TITLE
Disable clustering?

### ISSUE THREAD

**Issue by LeLunZ** [googlemaps/js-markerclusterer#441]
It would be nice to be able to disable clustering, and then display all markers.
Or that would also be possible by changing the algorithm while running to NoopAlgorithm.

Is it possible to implement that somehow? Or should I just clear all markers and add them again as normal markers to the map?

Another Question: is this project actually maintained?

**Comment by enkr1** [comment]
Hi @LeLunZ, I found a hacky way to disable the cluster by declaring it like:

```js
new MarkerClusterer(markers, map)
// Instead of
new MarkerClusterer({ markers, map })
```

And it works just fine. 

> I am looking for the same solution online but don't have the luck to find any ...

**Comment by amuramoto** [comment]
You can use some of the protected functions and props to do this. I think we should probably just make these public so that using ts-ignore isn't required, but I haven't been able to look into if there are any broader implications to doing that.

```
/* display all markers and hide the cluster icons */
// @ts-ignore
markercluster.markers.forEach((marker) => {
  marker.setMap(markercluster.getMap());
});
// @ts-ignore
markercluster.clusters.forEach((cluster) => {
  cluster.marker.setMap(null);
});

/* re-hide the markers then re-render the clusters
// @ts-ignore
markercluster.markers.forEach((marker) => {
  marker.setMap(null);
});
// @ts-ignore
markercluster.renderClusters();
```

And yes, this repo is maintained =)

**Comment by kathesama** [comment]
> You can use some of the protected functions and props to do this. I think we should probably just make these public so that using ts-ignore isn't required, but I haven't been able to look into if there are any broader implications to doing that.
> 
> ```
> /* display all markers and hide the cluster icons */
> // @ts-ignore
> markercluster.markers.forEach((marker) => {
>   marker.setMap(markercluster.getMap());
> });
> // @ts-ignore
> markercluster.clusters.forEach((cluster) => {
>   cluster.marker.setMap(null);
> });
> 
> /* re-hide the markers then re-render the clusters
> // @ts-ignore
> markercluster.markers.forEach((marker) => {
>   marker.setMap(null);
> });
> // @ts-ignore
> markercluster.renderClusters();
> ```
> 
> And yes, this repo is maintained =)

Works for me, TY
