### ISSUE TITLE
google.maps.event.addDomListener() is deprecated, use the standard addEventListener() method instead

### ISSUE THREAD

**Issue by nolimitdev** [googlemaps/js-markerclusterer#532]
#### Environment details

OS type and version: does not matter
Library version: any version including latest 5.1.3

#### Steps to reproduce

Just use MarkerClusterer and warning is shown in console.

#### Code example

```
new MarkerClusterer(googleMap, mapMarkers, { maxZoom : 14, imagePath: '...' });
```

#### Stack trace
```
google.maps.event.addDomListener() is deprecated, use the standard addEventListener() method instead
        https://developer.mozilla.org/docs/Web/API/EventTarget/addEventListener
  The feature will continue to work and there is no plan to decommission it.
```

**Comment by nemanjacosovic** [comment]
@lafllamme it has been said by @amuramoto that some things (like support for Advanced Markers) will be done with GA, but we don't know the date yet. The project seemed to have died down at one point as for over a month there were only 4 lines changed (with 26 commits). Sorry I couldn't help more.

**Comment by vicb** [comment]
@amuramoto I think this can be closed? It doesn't look like `addDomListener` is called any more.
