### ISSUE TITLE
I get the same error as the one I clipped since yesterday.

### ISSUE THREAD

**Issue by cyberprophet** [googlemaps/js-markerclusterer#669]
![20230606_134324](https://github.com/googlemaps/js-markerclusterer/assets/48705422/7d9bd563-6499-4d92-b80e-5c4b4635f1fb)
![20230606_134425](https://github.com/googlemaps/js-markerclusterer/assets/48705422/53b72253-e8bf-4a67-9703-1b01c83922cd)
![20230606_134406](https://github.com/googlemaps/js-markerclusterer/assets/48705422/6e0e30dc-8b82-452c-919b-0f1632566157)
![20230606_134345](https://github.com/googlemaps/js-markerclusterer/assets/48705422/fae7ff28-1e43-4e45-86b8-82730f13542f)

**Comment by vicb** [comment]
It looks like an issue with loading the Google Maps API and not related to this lib.

Have you tried to not instantiate this lib and only display a map to check if you still have the same issue?

**Comment by cyberprophet** [comment]
a problem with the address above "https://github.com/googlemaps/js-api-loader ".
