### ISSUE TITLE
Avoid direct assignment of innerHTML for Advanced Marker-based cluster pins

### ISSUE THREAD

**Issue by wangela** [googlemaps/js-markerclusterer#729]
renderer.ts [uses innerHTML ](github.com/googlemaps/js-markerclusterer/blob/main/src/renderer.ts#L131)to define a pin element based on an inline SVG. This may trigger warnings about XSS vulnerabilities. 

Recommended remedies:

- (Preferred) Follow the pattern in the [Advanced Markers SVG customization guide](https://developers.google.com/maps/documentation/javascript/advanced-markers/graphic-markers#inline-svg)
- Replace the full match with: safeElement.setInnerHtml(div, sanitizeHtmlAssertUnchanged(svg))

**Comment by usefulthink** [comment]
fixed in #744
