### ISSUE TITLE
delete clusters

### ISSUE THREAD

**Issue by enricCostas** [googlemaps/js-markerclusterer#77]
There some complete example for delete markers and clusters?

I can't use the delete() method correctly.

The response is delete is not a function

Thank you

**Comment by jpoehnelt** [comment]
Checkout [examples/updates.ts](https://github.com/googlemaps/js-markerclusterer/blob/main/examples/updates.ts), live at https://googlemaps.github.io/js-markerclusterer/public/updates/.

Reference docs for the `MarkerClusterer` class: https://googlemaps.github.io/js-markerclusterer/classes/MarkerClusterer.html
