### ISSUE TITLE
How do I implement the imagePath property in the latest version of the api?  (I'm use AngularJS)

### ISSUE THREAD

**Issue by Tatanstii** [googlemaps/js-markerclusterer#895]
Previously, to define the marker, you added the following properties.

```javascript
$scope.markerClusterTecnicos = new markerClusterer.MarkerClusterer({
    map: $scope.map, 
    markers: $scope.markers, 
    imagePath: 'images/markerclusterer/tecnicos/m',
    maxZoom: 12
});
```

Somehow the imagePath was autocompleted at the time of displaying it on the map, but in the new version the imagePath property was removed, how can I migrate this function, taking into account that I do not know how to get the name of the image (m1.png, m2.png, etc ...).

**Comment by thisisjamessmith** [comment]
Did you come up with a solution for this?

**Comment by openapphub** [comment]
Did you come up with a solution for this?
